url: https://y7kim.github.io
baseurl: /

# Site settings
title: Ag Stephens
email: ag.stephens@stfc.ac.uk
url: https://github.com/agstephens/agstephens.github.io
description: "I have over 20 years of working in environmental data management, software development and managing services. During my time at CEDA, I have developed, deployed and managed operational services in support of the UK Climate Projections (UKCP), the Copernicus Climate Change Service (C3S) and many other CEDA services. I have worked on a number of high-profile atmospheric and climate projects, including CMIP5/6 and participating the Ear th System Grid Federations (ESGF)."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: STFC
  - line: RAL, Oxon.

# Build settings
markdown: kramdown
permalink: pretty
